stages:
  - build
  - test
  - deploy

variables:
  CI_TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  REPO_URL: http://repo-staging.dc.prozorro.gov.ua/repos/helm/
  MONGODB_ROOT_PASSWORD: example
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: admin



build:
  image: docker:git
  stage: build
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - branches
    - tags

test:
  image: python:3.8
  stage: test
  tags:
    - kube-dev
  services:
    - "bitnami/mongodb:latest"
    - "couchdb:1.6"
  before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip install pytest pytest-asyncio coverage
  script:
    - echo '127.0.0.1:27017 mongodb' >> /etc/hosts
    - echo '127.0.0.1:5984 couchdb' >> /etc/hosts
    - cd tests && coverage run -m pytest
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

review:
  stage: deploy
  dependencies:
    - build
  tags:
    - shell
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://api.${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/tenders
    on_stop: stop_review
    auto_stop_in: 1 day
  variables:
    API_TAG: "2.6.20"
    TAG: $CI_COMMIT_REF_SLUG
    API_HOST: http://api.${CI_COMMIT_REF_SLUG}.$K8S_DOMAIN
  script:
    - helm3 repo add prozorro $REPO_URL
    - helm3 repo update
    - helm3 --debug upgrade $CI_COMMIT_REF_SLUG --install prozorro/prozorro --namespace dev-prozorro
          --set prozorro-api.image.tag=$API_TAG
          --set deployAuctions=false
          --set deployAuction=true
          --wait
    - helm3 --debug upgrade ${CI_COMMIT_REF_SLUG}-chronograph --install prozorro/prozorro-chronograph --namespace dev-prozorro
          --set chronograph.container.environment.PUBLIC_API_HOST=$API_HOST
          --wait
  only:
    - branches
  except:
    - master
  when: manual


stop_review:
  stage: deploy
  script:
    - helm3 delete $CI_COMMIT_REF_SLUG
    - helm3 delete $CI_COMMIT_REF_SLUG-chronograph
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  only:
    - branches
  except:
    - master
  when: manual
