stages:
  - test
  - build

test:
  image: python:3.8
  only:
    - branches
  when: manual
  services:
    - couchdb:1.6
  script:
    - echo '127.0.0.1 couchdb' >> /etc/hosts
    - pip install pytest
    - git clone https://github.com/ProzorroUKR/openprocurement.api.git src/opcr
    - pip install -e .
    - cp etc/*.ini src/opcr/etc/
    - docker compose up api -d
    - sleep 20
    - pytest tests/

docker build:
  image: docker:git
  stage: build
  only:
    - branches
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: fetch
