stages:
  - test
  - build
  - deploy

variables:
  CI_TAG: ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  REPO_URL: http://repo-staging.dc.prozorro.gov.ua/repos/helm/

test:
  image: python:3.8
  only:
    - branches
  when: manual
  services:
    - couchdb:1.6
  script:
    - echo '127.0.0.1 couchdb' >> /etc/hosts
    - pip install pytest
    - git clone https://github.com/ProzorroUKR/openprocurement.api.git src/opcr
    - pip install -e .
    - cp etc/*.ini src/opcr/etc/
    - docker compose up api -d
    - sleep 20
    - pytest tests/

build:
  image: docker:git
  stage: build
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - branches
    - tags


review:
  stage: deploy
  dependencies:
    - build
  tags:
    - shell
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://api.${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/2.5/tenders
    on_stop: stop_review
    auto_stop_in: 1 day
  variables:
    API_TAG: "2.6.20"
    FRONT_TAG: "0.2.11"
    TAG: $CI_COMMIT_REF_SLUG
  script:
    - helm repo add prozorro $REPO_URL
    - helm repo update
    - helm --debug upgrade $CI_COMMIT_REF_SLUG --install prozorro/prozorro --namespace dev-prozorro
          --set deployAuctions=false
          --set deployAuction=true
          --set prozorro-auction.frontend.image.tag=$FRONT_TAG
          --wait
  only:
    - branches
  when: manual


stop_review:
  stage: deploy
  script:
    - helm delete $CI_COMMIT_REF_SLUG --purge
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  only:
    - branches
  when: manual