stages:
  - test
  - build

test:
  image: python:3.8
  only:
    - branches
  when: manual
  services:
    - couchdb:1.6
  script:
    - echo '127.0.0.1 couchdb' >> /etc/hosts
    - pip install pytest
    - git clone https://github.com/ProzorroUKR/openprocurement.api.git
    - pip install -e .
    - cp etc/*.ini openprocurement.api/etc/
#    - pytest tests/

docker build:
  image: docker:git
  stage: build
  only:
    - branches
  when: manual
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#   - LATEST_MASTER_COMMIT=$(git log -n 1 origin/master --pretty=format:"%H")
#   - if [ "$LATEST_MASTER_COMMIT" = "$CI_COMMIT_SHA" ]; then EXTRA_TAGS="-t $CI_REGISTRY_IMAGE:latest"; fi
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $EXTRA_TAGS .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   - if [ "$LATEST_MASTER_COMMIT" = "$CI_COMMIT_SHA" ]; then docker push $CI_REGISTRY_IMAGE:latest; fi
  variables:
    GIT_STRATEGY: fetch
