version: '3'
services:
  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
    logging:
      driver: "none"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    logging:
      driver: "none"

  chronograph:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - API_OPT_FIELDS=status,auctionPeriod,lots,next_check
      - PUBLIC_API_HOST=https://lb-api-sandbox-2.prozorro.gov.ua
      - MONGODB_URL=mongodb://root:example@mongo:27017
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - "./src:/app"
