version: '3'
services:
  mongo:
    hostname: mongo
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ROOT_PASSWORD: example
    logging:
      driver: "none"
    ports:
    - 27017:27017

  chronograph:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - API_OPT_FIELDS=status,auctionPeriod,lots,next_check
      - PUBLIC_API_HOST=https://lb-api-sandbox-2.prozorro.gov.ua
      - MONGODB_URL=mongodb://root:example@mongo:27017
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - "./src:/app"

  couchdb:
    image: "couchdb:1.6"
    ports:
      - 5984:5984
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin

  api:
    build: src/opcr
    environment:
      SANDBOX_MODE: 'True'
    depends_on:
      - couchdb
      - mongo
    volumes:
      - "./src/opcr:/api/src/openprocurement:delegated"
      - "./src/opcr/docs:/api/docs:delegated"
      - "./src/opcr/etc:/api/etc:delegated"
    ports:
      - "8000:80"
    command: [ "gunicorn", "--bind", "0.0.0.0:80", "-k", "gevent", "--paste", "etc/service.ini", "--graceful-timeout=60", "--timeout=3600" ]
